# Versão da API Kubernetes que vai ser usada
apiVersion: apps/v1

# Tipo do objeto que vamos criar
kind: Deployment

metadata:
  # Nome do objeto que estamos criando
  name: lifters-deployment
  
spec:
  selector:
    matchLabels:
      # Referência ao pod que será criado/já existe
      app: lifters-pod
  # Número de pods que serão criados
  replicas: 1
  template:
    metadata:
      labels:
        # Nome do(s) pod(s) que será/serão criado(s)
        app: lifters-pod
    spec:
      containers:
          # Aqui é o nome da imagem que será utilizada
        - image: lifters-image
          # Definimos aqui qual será o nome do container
          name: lifters-container
          # Este comando diz para o Docker não procurar
          # a imagem externamente (no Docker Hub)
          imagePullPolicy: Never
          ports:
              # Especificação de porta do container
            - containerPort: 8080